spring:
  application:
    name: cardcollection
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create
      show-sql: true
  sql:
    init:
      mode: always
#      schema-locations: classpath:db/migration/V1__initialize_tables.sql